# Create an externally accessible network named 'ext_network'.
- name: Attach the floating ip with virtual IP
  hosts: localhost
  gather_facts: no
  tasks:
    - shell:
          #'openstack floating ip create --port Virtual-IP ext-net'
          'openstack server list'
    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        minutes: 1
    - shell:
          'openstack floating ip list -f csv -c "Floating IP Address"| grep "[0-9]"'
      register: hello
    - debug: msg='The Apache2 web server is available at {{ hello.stdout }}'