# Create a new instance
- name: Launch a compute instance for Load Balancer
  hosts: localhost
  gather_facts: no
  tasks:
    - name: launch an instance
      openstack.cloud.server:
        state: present
        auth:
          auth_url: http://sdncloud91cn.netcracker.com:5000/v3/
          username: ruku
          password: wiiVee5rei
          project_name: ruku-project
        name: LB-2
        #region_name: region-b.geo-1
        availability_zone: nova-1
        image: ubuntu_18.04_w_root
        flavor: m1.medium
        #network: int-net
        nics: 
          - net-name: net
          - net-name: int-net
        key_name: backend-1
        timeout: 200
        security_groups: default
        auto_floating_ip: false
        #floating_ips:
        # - 10.101.205.124
        userdata: |
          {%- raw -%}#!/bin/bash
          # update repo list
          sudo touch /etc/apt/sources.list.d/nc_bionic.list
          sudo bash -c "echo 'deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic main restricted
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic-updates main restricted
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic universe
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic-updates universe
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic multiverse
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic-updates multiverse
          deb http://yumsrv03cn.netcracker.com/deb/ubuntu/ bionic-backports main restricted universe multiverse' >> /etc/apt/sources.list.d/nc_bionic.list"
          sudo apt update -y
          # Install and update keepalived && haproxy
          sudo apt install keepalived haproxy -y && sudo systemctl enable keepalived haproxy
          sudo bash -c 'echo "vrrp_instance vrrp_group_1 {
          state BACKUP
          interface ens3
          virtual_router_id 1
          priority 50
          authentication {
            auth_type PASS
            auth_pass password
            }
          virtual_ipaddress {
            10.1.0.9/24 brd 10.1.0.255 dev ens3
          }
          }" > /etc/keepalived/keepalived.conf'
          sudo touch /etc/haproxy/haproxy.cfg
          sudo bash -c "echo 'frontend haproxy-main
            bind *:80
            option forwardfor
            default_backend apache_webservers

          backend apache_webservers
            balance roundrobin
            server websvr1      192.168.0.20:80 check
            server websvr2      192.168.0.12:80 check' > /etc/haproxy/haproxy.cfg"
          
          {% endraw %}